#!/bin/bash
# ---------------------------------------------------------------
# PDF Viewer Platform — Docker Entrypoint
# Writes config files from environment variables, then starts Apache
# ---------------------------------------------------------------
set -e

echo "[pdfviewer] Starting configuration..."

CONFIG_DIR="/var/www/html/config"
DB_CONFIG="$CONFIG_DIR/database.php"
APP_CONFIG="$CONFIG_DIR/app.php"

# Write database config from environment variables
cat > "$DB_CONFIG" <<PHP
<?php
// Auto-generated by Docker entrypoint — do not edit manually
return [
    'host'     => '${DB_HOST:-db}',
    'port'     => ${DB_PORT:-3306},
    'name'     => '${DB_NAME:-pdf_viewer}',
    'username' => '${DB_USER:-pdfviewer}',
    'password' => '${DB_PASS:-secret}',
    'charset'  => 'utf8mb4',
    'options'  => [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ],
];
PHP

# Write app config only if it doesn't already exist (preserves manual edits)
if [ ! -f "$APP_CONFIG" ]; then
    cp "$CONFIG_DIR/app.php.example" "$APP_CONFIG"
    # Patch base_url
    sed -i "s|'base_url'.*=>.*'[^']*'|'base_url' => '${APP_BASE_URL:-http://localhost:8080}'|" "$APP_CONFIG"
    echo "[pdfviewer] App config created from example."
fi

# Fix permissions
chown -R www-data:www-data /var/www/html/uploads /var/www/html/config
chmod -R 775 /var/www/html/uploads /var/www/html/config

echo "[pdfviewer] Config ready. Starting Apache..."

# Hand off to Apache
exec apache2-foreground "$@"
